name: Feature Request
description: Suggest a new feature or enhancement for MathModelAgent
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - Code Interpreter
        - Multi-Agent System
        - Paper Generation
        - LLM Integration
        - Documentation
        - DevOps/CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who will benefit from this feature and how?
      placeholder: Describe the benefits of this feature...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how to implement this, please share
      placeholder: Technical implementation details or suggestions...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or mockups if applicable
      placeholder: Links to similar features in other projects, mockups, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests before creating this one
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to help implement this feature if guidance is provided
          required: false
